"""Constants for SaltNZ."""

import logging

FPGA_PORT = 5555
MSL_RAMP_PORT = 5556

FPGA_INTERCEPT_MHZ = 2.046338
SWEEP_RATE_MHZ_PER_MS = 1.257
DISCARD_MARGIN_SAMPLES = 0.1
WRAPPED_RANGE_OFFSET_MHZ = 25

logger = logging.getLogger(__name__)
